name: 'Build'

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checkout project files
      - uses: actions/checkout@v3

      # Setup Java
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
          cache: 'maven'

      # Build project
      - name: Build with Maven
        run: 'mvn -B -Duser.name="GitHub Runner on $GITHUB_REPOSITORY (id=$GITHUB_RUN_ID)" clean package'

      # Upload build artifacts
      - name: 'Upload Build Artifact: ServerJars-*.jar'
        uses: actions/upload-artifact@v2
        with:
          name: ServerJars-artifacts
          path: ./target/ServerJars-*.jar
